package edu.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import edu.model.batteries.BatteryGrid;
import edu.model.batteries.GravitationalBattery;
import edu.controllers.Controller;

public class TestForm extends JFrame
{
	//region Form items
	private JPanel panelMain;
	private JPanel panelLeft;
	private JPanel panelRight;
	private JPanel panelBottom;
	private JButton btnBattery;
	private JButton btnShowGrid;
	private JButton btnEnergy;
	private JLabel lblName;
	private JLabel lblHeight;
	private JLabel lblMass;
	private JTextField txtName;
	private JTextField txtMass;
	private JTextField txtHeight;

	private static JFrame frame = new JFrame("TestForm");
	private static JFrame newTestForm = new JFrame("NewTestForm");
	//endregion

	public TestForm()
	{
		super("Main Panel");

		//region Listeners
		btnBattery.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				// Add the gravitational battery to the grid
				Controller.addBattery(txtName.getText(), Double.parseDouble(txtMass.getText()), Double.parseDouble
						(txtHeight.getText()));

				JOptionPane.showMessageDialog(frame, "Added " + txtName.getText() + " to the battery grid.");
				//TODO: Add update() functionality
			}
		});

		btnShowGrid.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{

			}
		});
		//endregion
		btnEnergy.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				frame.setContentPane(new NewTestForm().panelMain);
				frame.pack();
			}
		});
	}

	//region Methods
	private static void update()
	{

	}
	//endregion

	public static void main(String[] args)
	{
		// TestForm JFrame
		frame.setContentPane(new TestForm().panelMain);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);

		// Other JFrames
//		newTestForm.setContentPane(new NewTestForm().panelMain);
//		newTestForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//		newTestForm.pack();
//		newTestForm.setVisible(true);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		panelMain = new JPanel();
		panelMain.setLayout(new BorderLayout(0, 0));
		panelMain.setBackground(new Color(-12828863));
		panelLeft = new JPanel();
		panelLeft.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
		panelMain.add(panelLeft, BorderLayout.WEST);
		lblName = new JLabel();
		lblName.setText("Battery Name:");
		panelLeft.add(lblName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		lblHeight = new JLabel();
		lblHeight.setText("Maximum Height in Meters:");
		panelLeft.add(lblHeight, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		lblMass = new JLabel();
		lblMass.setText("Mass in Kilograms:");
		panelLeft.add(lblMass, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		panelRight = new JPanel();
		panelRight.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
		panelMain.add(panelRight, BorderLayout.EAST);
		txtName = new JTextField();
		panelRight.add(txtName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		txtMass = new JTextField();
		panelRight.add(txtMass, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		txtHeight = new JTextField();
		panelRight.add(txtHeight, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		panelBottom = new JPanel();
		panelBottom.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		panelMain.add(panelBottom, BorderLayout.SOUTH);
		btnBattery = new JButton();
		btnBattery.setText("Battery");
		panelBottom.add(btnBattery);
		btnShowGrid = new JButton();
		btnShowGrid.setText("Show Grid");
		panelBottom.add(btnShowGrid);
		btnEnergy = new JButton();
		btnEnergy.setText("Energy");
		panelBottom.add(btnEnergy);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return panelMain;
	}
}
